### ISSUE TITLE
load_model fails with TypeError: unsupported operand type(s) for /: 'PosixPath' and 'ModelPrivateAttr'

### ISSUE THREAD

**Issue by sooheon** [peng-lab/BaSiCPy#133]
https://github.com/peng-lab/BaSiCPy/blob/f4eac9bbca2a4cffec01c26aeb2837b80327905c/src/basicpy/basicpy.py#L801C22-L801C22

load_model being a classmethod, cls._profiles_fname and cls._settings_fname are not instantiated when called, so are not recognized as strings and can't be added to Path with / op.

**Comment by yfukai** [comment]
Hi, thanks @sooheon for finding this! I believe this is already fixed in the newest version by setting the filename outside the class. I'll close this for now but please feel free to reopen this!

https://github.com/peng-lab/BaSiCPy/blob/07d438ed58b8a9ab154a41a4d57e44de6b631fe6/src/basicpy/basicpy.py#L835-L877
