### ISSUE TITLE
`transform` over `predict`

### ISSUE THREAD

**Issue by yfukai** [peng-lab/BaSiCPy#40]
When we consider `sklearn` style, `transform` and `fit_transform` seem to be better terms (ex: used for `PCA`).

**Comment by Nicholas-Schaub** [comment]
After looking at the description, I agree with this.

I generally dislike rehashing decisions we have made without significant reason, because that opens the door to scrupulosity and slows down the development process. I'm not saying we do this now, but I want to bring this point up now so that we don't fall into a pit.

I think fit/predict works fine, but fit/transform is more appropriate given the sklearn package. I'm okay with either, but I default to leaving it as is.

**Comment by tdmorello** [comment]
I think `transform` better describes the operation and is more obvious for the user.

**Comment by Nicholas-Schaub** [comment]
I think that settles it then. Let's do `transform`.
